apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcatalogueapp
  labels:
    app: foodcatalogueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodcatalogueapp
  template:
    metadata:
      name: foodcatalogueapp
      labels:
        app: foodcatalogueapp
    spec:
      containers:
        - name: foodcatalogueapp
          image: macktb/foodcatalogue-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mysql-username
                  name: secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: secret
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: foodcataloguedb_url
                  name: configmap
---
apiVersion: v1
kind: Service
metadata:
  name: foodcatalogue-service
spec:
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: foodcatalogueapp
      