apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp
  labels:
    app: orderapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      name: orderapp
      labels:
        app: orderapp
    spec:
      containers:
        - name: orderapp
          image: macktb/order-service:9
          imagePullPolicy: Always
          ports:
            - containerPort: 9094
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djdk.tls.client.protocols=TLSv1.2"
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: orderdb_url
                  name: configmap
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "orderdb"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: orderapp
  ports:
    - port: 9094
      protocol: TCP
      targetPort: 9094
